create table employee(
	employeeid number GENERATED ALWAYS AS IDENTITY primary key,
	employeename nvarchar2(100),
	phone nvarchar2(20),
	address nvarchar2(100),
	role nvarchar2(100),
	salary int,
	birthday date,
	gender nvarchar2(20)
	);

create table account(
	username nvarchar2(100) primary key,
	password nvarchar2(100),
	employeeid int,
	foreign key(employeeid) references employee(employeeid));


create table room(
	roomid number GENERATED ALWAYS AS IDENTITY primary key,
	roomname nvarchar2(100),
	type nvarchar2(200),
	priceperhour int,
	status nvarchar2(50)
);

create table service(
	serviceid NUMBER GENERATED by default on null as IDENTITY,
	servicename nvarchar2(100),
	price int,
    primary key (serviceid)
);

drop table service;


INSERT INTO employee ( employeename, phone, address, role, salary, birthday, gender) VALUES
( 'Ph?m Ti?n S?', '0868686868', 'Gia Lai City', 'Admin', 9999, to_date('10/02/2000' ,'dd/mm/yyyy'), 'Nam');
INSERT INTO employee ( employeename, phone, address, role, salary, birthday, gender) VALUES
( 'Ph?m V?n Nh?n', '087878787', 'Bình Thu?n City', 'Staff', 99999, to_date('10/07/2000' ,'dd/mm/yyyy'), 'Nam');
INSERT INTO employee ( employeename, phone, address, role, salary, birthday, gender) VALUES
( 'q?ewe', '089898989', 'Hw City', 'Staff', 9999, to_date('10/04/2000' ,'dd/mm/yyyy'), 'Nam');

INSERT INTO account (username, password, employeeid) VALUES('pts', 'pts', 1);


INSERT INTO room ( roomname, type, priceperhour, status) VALUES
( 'A1.1', 'Phòng Th??ng', 150000, NULL);
INSERT INTO room ( roomname, type, priceperhour, status) VALUES
( 'A1.2', 'Phòng Th??ng', 150000, NULL);
INSERT INTO room ( roomname, type, priceperhour, status) VALUES
( 'A1.3', 'Phòng Th??ng', 150000, NULL);
INSERT INTO room ( roomname, type, priceperhour, status) VALUES
( 'A1.4', 'Phòng Th??ng', 150000, NULL);


select employeeid from account where username = 'pts' and password = 'pts';

select * from account where employeeid='1';


select * from account where employeeid='1';

update account set password='pts1' where username = 'pts' and employeeid = '1';

select * from employee order by employeeid ASC; 

insert into service(servicename ,price) values ('bò húc',12000);
insert into service(servicename ,price) values ('trái cây',50000);